### ISSUE TITLE
Problem when installing

### ISSUE THREAD

**Issue by michaldybczak** [pdf/kdeconnect-chrome-extension#3]
I downloaded linux package, unzipped, opened terminal in file location and run:

`sudo ./kdeconnect-chrome-extension -install`

Unfortunately it gave me those errors:

panic: runtime error: slice bounds out of range

```
goroutine 1 [running]:
panic(0x60f3c0, 0xc420010120)
	/usr/lib/go/src/runtime/panic.go:500 +0x1a1
github.com/pdf/kdeconnect-chrome-extension/vendor/github.com/godbus/dbus.sessionBusPlatform(0x651417, 0x18, 0x0)
	/storage/workspace/golang/src/github.com/pdf/kdeconnect-chrome-extension/vendor/github.com/godbus/dbus/conn_other.go:27 +0x2d4
github.com/pdf/kdeconnect-chrome-extension/vendor/github.com/godbus/dbus.SessionBusPrivate(0x0, 0x0, 0x0)
	/storage/workspace/golang/src/github.com/pdf/kdeconnect-chrome-extension/vendor/github.com/godbus/dbus/conn.go:102 +0x11d
github.com/pdf/kdeconnect-chrome-extension/vendor/github.com/godbus/dbus.SessionBus(0x0, 0x0, 0x0)
	/storage/workspace/golang/src/github.com/pdf/kdeconnect-chrome-extension/vendor/github.com/godbus/dbus/conn.go:77 +0xe3
main.newDeviceList(0x78d19f, 0x64a737, 0x7)
	/storage/workspace/golang/src/github.com/pdf/kdeconnect-chrome-extension/dbus.go:363 +0x26
main.init.1()
	/storage/workspace/golang/src/github.com/pdf/kdeconnect-chrome-extension/main.go:113 +0x6a
main.init()
	/storage/workspace/golang/src/github.com/pdf/kdeconnect-chrome-extension/messaging.go:64 +0x30a

```

So basically, plugin doesn't work, because it always shows no device and that it needs upgrading.

**Comment by pdf** [comment]
The problem appears to be in the [godbus](https://github.com/godbus/dbus) project.  So that I can lodge a useful issue with them, can you post the output of `dbus-launch` and `dbus-launch --version` from a terminal?  It should look something like:

```
$ dbus-launch
DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-MCk0C4Q6gP,guid=e64c50603a79f9dca7da758e20a3b5a0
DBUS_SESSION_BUS_PID=8610
$ dbus-launch --version
D-Bus Message Bus Launcher 1.10.16
Copyright (C) 2003 Red Hat, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Can you also tell me which Linux distribution (and version) you're using?

_PS - Sorry for the delay in responding - there appears to be something wrong with notifications on this repository, and I am not receiving emails or web notifications for issues on this specific repo.  I've sent an email to Github about it, please forgive me if I do not respond promptly while they (hopefully) sort it out._

**Comment by pdf** [comment]
@michaldybczak any chance you can provide the requested information so that we can get this sorted out?

**Comment by michaldybczak** [comment]
Sorry, didn't notice your previous post.
I tried the update process and this time everything went fine... It asked me for a browser, gave some id, I restarted the browser and now it sees the device. I have no idea why it didn't work before. But I had some system updates between now and then. Anyway, the situation is fixed.
