### ISSUE TITLE
Cannot install host application

### ISSUE THREAD

**Issue by GeorgiKarapetrov** [pdf/kdeconnect-chrome-extension#33]
**Describe the bug**
The host application is not a shell script. Maybe this is embarrassing and I should know. How can I execute `./kdeconnect-chrome-extension -install` in terminal, (following the instructions here on Git,) if it is not a shell script?

**To Reproduce**
1. Go to [latest release](https://github.com/pdf/kdeconnect-chrome-extension/releases/tag/v0.1.3)
2. Download the _tar.xz_ archive
3. Extract the _kdeconnect-chrome-extension_ application
4. run # `./kdeconnect-chrome-extension -install`
5. See error `bash: ./kdeconnect-chrome-extension: Permission denied`
or
4. run # `bash kdeconnect-chrome-extension -install`
4. See error `kdeconnect-chrome-extension: kdeconnect-chrome-extension: cannot execute binary file`

**Expected behavior**
I expected the application to install.

**Desktop:**
 - Linux Kernel 5.4.30-1-MANJARO, (Rolling Manjaro 64-bit)
 - Browser Firefox 75.0 (64-bit)
 - kdeconnect-cli version 1.4.0
 - kdeconnect-cli devices - moto g(6) plus: (paired and reachable)
 - kdeconnect-chrome-extension version 0.1.3

**Smartphone (please complete the following information):**
 - Device: Motorola g6+
 - OS: Android Pie

**Additional**
The gsconnect extension works with Gnome desktop and gsconnect. I would really prefer using KDEConnect if I may. Hopefully, I am running the wrong command.

**Comment by pdf** [comment]
For some reason your archiver or file system is not preserving the executable bit on the extracted file, or you're running an incompatible architecture:

```
tar -xvf kdeconnect-chrome-extension*.tar.xz
```

The above works correctly here. If it doesn't for you, you can try `chmod +x kdeconnect-chrome-extension`, if that fails, there is something unusual about the filesystem you're extracting this to (is it mounted with `noexec` or something?

Are you on the supported architecture (Linux, x86_64)? If you're running a 32-bit, or an alternative architecture, or OS, this binary won't work, and you'd need to build from source for your arch.

I haven't been building 32-bit binaries, because I didn't think there were many people using 32-bit processors anymore, and a number of distros are phasing out 32-bit support.

**Comment by GeorgiKarapetrov** [comment]
Thank you, you were right. I re-extracted the archive on an _ext4_ drive. The host application installs.
The extension connects and sends pages to my phone now.
