### ISSUE TITLE
send links from android phone to desktop

### ISSUE THREAD

**Issue by elypter2** [pdf/kdeconnect-chrome-extension#47]
It would be very useful if you could send links the other way too. the addon isnt available on mobile firefox but that feature would be great if it was possible to make it work with the android version of kde konnect too.

**Comment by pdf** [comment]
You can use the share workflow on Android (some browsers do it better than others, but they all do it), which should pop straight to your browser on desktop. For most Android browsers, you just hit the 3-dots menu, hit the share icon and choose KDE Connect. Some browsers will remember the last share target so you can do it in two taps.

Since the workflow is "good enough" on mobile, the number of browsers that support extensions is low, and I'm not certain any of them support native hosts, _and_ it would be quite some effort to get the native host deployed on Android, I have no plans to target mobile.

Going to close this out.
